server:
  servlet:
    encoding:
      force: true
      charset: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-green.cmoif9215vlk.ap-northeast-2.rds.amazonaws.com:3306/greenbook?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: {username}
    password: {password}
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: update
    database: mysql
  redis:
    host: redis.yenpew.ng.0001.apn2.cache.amazonaws.com
    port: 6379

redis:
  archive:
    prefix: arc
  review:
    prefix: rev

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE